local lib = loadstring(game:HttpGet("https://sonic998.github.io/sonichub/UI.lua"))()
local functions = loadstring(game:HttpGet("https://sonic998.github.io/sonichub/functions/"..game.PlaceId.."/InnovationArcticBase.lua"))()

local win = lib:CreateWindow("SonicHub - Innovation Arctic Base")
local localplayer = win:Page("LocalPlayer")
local teleport = win:Page("Teleport")
local misc = win:Page("Misc")
local Games = win:Page("Games")
local TeleportService = game:GetService("TeleportService")

Games:Label("-----Supported Games-----")
Games:Label("Titan Simulator")
Games:Button("^Join the game^", function()
TeleportService:Teleport(1122519450)
end)
Games:Label("Lifting Legends")
Games:Button("^Join the game^", function()
TeleportService:Teleport(5709572883)
end)
Games:Label("Innovation Inc Spaceship")
Games:Button("^Join the game^", function()
TeleportService:Teleport(331811267)
end)
Games:Label("Innovation Arctic Base")
Games:Button("^Join the game^", function()
TeleportService:Teleport(1033860623)
end)
Games:Label("Burping Simulator(Drinkhax)")
Games:Button("^Join the game^", function()
TeleportService:Teleport(1747207098)
end)
Games:Label("Zombie Attack")
Games:Button("^Join the game^", function()
TeleportService:Teleport(1240123653)
end)
Games:Label("Rabbit Simulator")
Games:Button("^Join the game^", function()
TeleportService:Teleport(1502601752)
end)
Games:Label("Gorilla Simulator")
Games:Button("^Join the game^", function()
TeleportService:Teleport(1378712700)
end)
Games:Label("Ultra Lifting Simulator")
Games:Button("^Join the game^", function()
TeleportService:Teleport(13928941253)
end)
Games:Label("Treasure Quest")
Games:Button("^Join the game^", function()
TeleportService:Teleport(2960777560)
end)
Games:Label("Adventure Up")
Games:Button("^Join the game^", function()
TeleportService:Teleport(3194820651)
end)

teleport:Button("Outside")

localplayer:Button("WalkSpeed", function()
speed()
end)

localplayer:Button("Inf Jump", function()
jump()
end)

misc:Button("Rejoin", function()
rejoin()
end)

misc:Button("Inf Yield", function()
infyield()
end)
  
misc:Button("Anti Afk", function()
AntiAfk()
end)
